### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by Negatil07** [Joachim26/SmallfishNPS#1]
How to Create a Makefile with Optimization? Im using Termux on android.

**Comment by Joachim26** [comment]
Difficult from scratch. For SmallfishNPS, which is obviously a SF clone, I have just adapted the newest SF makefile. PGO works great for SmallfishNPS on Termux with both gcc and clang.

**Comment by Joachim26** [comment]
For a more detailed answer better ask the guys on the Stockfish Discord server in the #help channel!
